### ISSUE TITLE
Noise in the normalised space?

### ISSUE THREAD

**Issue by bnaman50** [PAIR-code/saliency#30]
Hey guys, 

Thanks for providing the implementations of these famous/helpful algorithms. I really appreciate it. 

I was looking to use SmoothGrad in my project. On inspecting your code, I find it weird that you are adding noise (approx range - `-1.3 - 1.5`, with the default settings) in the normalized image space rather than adding it to the unnormalized image and then normalizing it (which was my initial understanding). Going by your code, it would mean that the distribution of the model input has been completely changed (range - `-2.3 - 2.5` something) which seems weird to me.

It would be really helpful if you could elaborate on it and confirm that this is correct. 

Thanks, 
Naman

**Comment by bwedin** [comment]
Late on this, but thank you for the question!

Yes you're reading the code correctly, the image is never re-normalized after adding noise, which is the intended behavior. The numbers you're citing are relatively small in the grand scheme of things: with stdev .15 and range [-1,1], >99% of noise will be less than [-1,1].

While having some features be out of the normalized range can be weird, re-normalizing the values would create a secondary perturbation: essentially greatly decreasing the contrast of the image. With your example, pixels in [-1,1] would be collapsed to [-.45,.37]. Examples here:

Input image:
![input](https://user-images.githubusercontent.com/22078567/127362762-04d1162b-459a-4044-883a-071b21d287e1.png)

Image + noise (out of range values clipped):
![noise](https://user-images.githubusercontent.com/22078567/127362814-26170622-96c5-491d-9e9d-2ee455e08464.png)

Image + noise, normalized to input range:
![renormalized](https://user-images.githubusercontent.com/22078567/127362856-430a63b9-70e9-4867-abf1-de34466eee58.png)

For some of the pre-trained models like Inception, the resulting maps will look mostly the same, since the model is trained to handle differences in brightness/contrast, and can usually handle images that are normalized differently. But for models that aren't trained on low-contrast versions, adding the extra normalization step may be worse than having some fractions of features out of the expected distribution. Let us know if you have any other questions!
