### ISSUE TITLE
The code of evaluation methods 

### ISSUE THREAD

**Issue by yh960520** [PAIR-code/saliency#39]
Is there the code of evaluation methods ? Thanks

**Comment by bwedin** [comment]
Thanks for your interest!

We don't have any plans to release the full pipeline, since that would also require releasing the images/metadata and models that we are evaluating on. We are thinking about how to release tools that will allow for evaluating different saliency methods with user-defined datasets and models, which would include things like information curves or localization metrics (given some generic ground truth attribution/label and saliency map). No plans in the near-term, but we have added it as a feature request for our internal tracking.
