### ISSUE TITLE
lack of Guided Backpropogation

### ISSUE THREAD

**Issue by zhixiongzh** [PAIR-code/saliency#67]
Hi,
in the example-pytorch.ipynb, it is said that Guided Backpropogation is implemented in the notebook, but I can't find this.

**Comment by bwedin** [comment]
That's a typo on our part, the core/pytorch versions don't have guided backprop currently. Since the only piece needed is call_model_function, we can't make any modifications to the graph. We want to try and add more support for pytorch in the same way we have additional support for TF1, but currently the recommended method for using pytorch is to use core.

**Comment by bwedin** [comment]
Corrected in https://github.com/PAIR-code/saliency/pull/71
