### ISSUE TITLE
The returned masks were all nan

### ISSUE THREAD

**Issue by irwenqiang** [PAIR-code/saliency#8]
After predicted 237 correctly. It failed becaused the returned masks were all nan
`# Compute the vanilla mask and the smoothed mask.   

vanilla_mask_3d = gradient_saliency.GetMask(im, feed_dict = {neuron_selector: prediction_class})
`
https://github.com/PAIR-code/saliency/blob/e96253955a8c8b9fe5f7e89daccbdc161473e089/saliency/base.py#L97

**values of vanilla_mask_3d:**
[[[nan nan nan]
  [nan nan nan]
  [nan nan nan]
  ...
  [nan nan nan]
  [nan nan nan]
  [nan nan nan]]

**Comment by irwenqiang** [comment]
It seems that x is of a parameter of y, so get not any dy/dx

**Comment by irwenqiang** [comment]
tensorflow r1.2 works well

**Comment by JarvisDevon** [comment]
I am getting the same result using Tensorflow Version

This problem however only occurs on models which do not perform well in the domain I am using (the majority of the saliency maps are NaN, however on occasion the model will provide a very dark saliency map). I have trained models which perform well in the domain and provide clear saliency maps.

Thus, I am curious if there is an interpretation for the NaN's or a conclusion that can be made. My feeling is that the NaN's occur due to the model's inability to develop strong or decisive weights. Would this be a logical cause for the NaNs?

**Comment by JarvisDevon** [comment]
I am getting the same result using Tensorflow Version 1.4.0

This problem however only occurs on models which do not perform well in the domain I am using (the majority of the saliency maps are NaN, however on occasion the model will provide a very dark saliency map). I have trained models which perform well in the domain and provide clear saliency maps.

Thus, I am curious if there is an interpretation for the NaN's or a conclusion that can be made. My feeling is that the NaN's occur due to the model's inability to develop strong or decisive weights. Would this be a logical cause for the NaNs?
